#!/usr/bin/env bash
# Usage: ./0-world_wide_web <domain> [subdomain]
# Display information about subdomains

subdomain_info () {
	record=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION' | tail -1 | tr ' \t' ' ' | cut -d' ' -f4,5)
    echo "$2 $record" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  subdomain_info "$1" "www"
  subdomain_info "$1" "lb-01"
  subdomain_info "$1" "web-01"
  subdomain_info "$1" "web-02"
elif [ "$#" == 2 ]
then
  subdomain_info "$1" "$2"
fi
