#!/usr/bin/env bash
# Installs and starts nginx web server
# Add index.html page

### Temporal env variable(s) ####
export WEB_ROOT="/var/www/html/"

apt-get -y update # update repository
apt-get -y install nginx # install server
ufw allow 'Nginx HTTP' # allow port 80 for Nginx
mkdir -p $WEB_ROOT # create room directory
echo "Hello World!" > $WEB_ROOT/index.html # create index page

### Start / restart server service ###
service nginx restart
