#!/usr/bin/env bash
# Installs, configures, and starts the server

apt-get -y update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
SERVER_CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
		rewrite ^ https://moleculesoft.net permanent;
	}
}"

export CONFIG="/etc/nginx/sites-enabled/default"
export BACKUP_DIR="./alx/nginx/server_conf"
mkdir $BACKUP_DIR -p
sudo cp $CONFIG $BACKUP_DIR"/default_"$(date +%Y%m%d%H%M%S).bak
echo "$SERVER_CONFIG" > $CONFIG

if [ "$(pgrep -c nginx)" -le 0 ]; then
	service nginx start
else
	service nginx restart
fi
