#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server

sudo apt-get -y update
apt-get -y install haproxy

server_config=\
"
frontend  MOLeCULE_Soft_frontend
        bind *:80
        mode http
        default_backend MOLeCULE_Soft_backend
backend MOLeCULE_Soft_backend
        balance roundrobin
        server 170349-web-01 35.175.132.210:80 check
        server 170349-web-02 35.153.232.176:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy restart
