#!/usr/bin/env bash
#daemon controller

file="/var/run/my_process.pid"
process="manage_my_process"

if [ "${1}" == "start" ]
then
    ./"$process" &
    echo "$!" > "$file"
    echo "$process started"
elif [ "${1}" == "stop" ]
then
    echo "$process stopped"
    kill "$(cat "$file")"
    rm "$file"
elif [ "${1}" == "restart" ]
then
    kill "$(cat "$file")"
    rm "$file"
    ./"$process" &
    echo "$!" > "$file"
    echo "$process restarted"
else
    echo "Usage: $process {start|stop|restart}"
fi

