#!/usr/bin/env bash
#enless loop trapping TERM signal

#SIGTERM handler
on_sigterm()
{
	echo "I am invincible!!!"
}

#register signal handler
trap on_sigterm TERM

while true;
do
	echo To infinity and beyond
	sleep 2
done
