#!/usr/bin/env bash
#prints 1 to 100 but will replace a number
#with FizzBuzz if is a multiple of 3 and 5
#Buzz if is a multiple of 5 only
#and Fizz if is a multiple of 3 only

i=1
while [ $i -le 100 ]
do
	if [ $((i % 15)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i % 5)) -eq 0 ]
	then
		echo "Buzz"
	elif [ $((i % 3)) -eq 0 ]
	then
		echo "Fizz"
	else
		echo "$i"
	fi
	i=$((i+1))
done
