#!/usr/bin/env bash
#Na comment be this

i=1
while [ $i -le 100 ]
do
	if [ $((i % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((i % 5)) -eq 0 ]
	then
		echo "Buzz"
	elif [ $((i % 15)) -eq 0 ]
	then
		echo "FizzBuzz"
	else
		echo "$i"
	fi
	i=$((i+1))
done
