#!/usr/bin/env bash
#reads the /etc/passwd file displaying some fields

file="/etc/passwd"
while IFS= read -r line;
do
	username=$(echo "$line" | cut -d':' -f1)
	userid=$(echo "$line" | cut -d':' -f3)
	home=$(echo "$line" | cut -d':' -f6)
	echo "$username:$userid:$home"
done < "$file"
