#!/usr/bin/env bash
#reads the /etc/passwd file displaying some fields as a story

file="/etc/passwd"
while IFS= read -r line;
do
	username=$(echo "$line" | cut -d':' -f1)
	password=$(echo "$line" | cut -d':' -f2)
	userid=$(echo "$line" | cut -d':' -f3)
	groupid=$(echo "$line" | cut -d':' -f4)
	more=$(echo "$line" | cut -d':' -f5)
	home=$(echo "$line" | cut -d':' -f6)
	command=$(echo "$line" | cut -d':' -f7)
	story="The user $username is part of the $groupid gang, \
lives in $home and rides $command. \
$userid's place is protected by the passcode $password, \
more info about the user here: $more"
	echo "$story"
done < "$file"
