#!/usr/bin/env bash
#loops 10 times printing 'Best School'
#while the loop is not running the 4th or
#while 8th time else it prints 'bad luck'
#or 'good luck' respectively

i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
