#!/bin/bash
# This script configures the ufw firewall
# to block all incoming traffic except for
# ssh(22), https(443) and http(80)

sudo ufw default deny incoming
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
